# revision 15878
# category Package
# catalog-ctan undef
# catalog-date undef
# catalog-license undef
# catalog-version undef
Name:		texlive-tex-virtual-academy-pl
Version:	20111104
Release:	2
Summary:	TeXLive tex-virtual-academy-pl package
Group:		Publishing
URL:		http://tug.org/texlive
License:	http://www.tug.org/texlive/LICENSE.TL
Source0:	http://mirrors.ctan.org/systems/texlive/tlnet/archive/tex-virtual-academy-pl.tar.xz
Source1:	http://mirrors.ctan.org/systems/texlive/tlnet/archive/tex-virtual-academy-pl.doc.tar.xz
BuildArch:	noarch
BuildRequires:	texlive-tlpkg
Requires(pre):	texlive-tlpkg

%description
TeXLive tex-virtual-academy-pl package.

#-----------------------------------------------------------------------
%files
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/TeX-pub.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/context/cont-ins.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/context/context.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/context/tytuly.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/cototex.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/fonty/back.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/fonty/font-abc.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/fonty/fonts_inst.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/fonty/index.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/fonty/nfss.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/fonty/qx-info.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/fonty/qx-table1.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/fonty/qx-table2.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/fonty/tpstyle.css
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/gify/artykul.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/gify/context.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/gify/cop.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/gify/grupa.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/gify/gust.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/gify/gustloge.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/gify/indexowanie.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/gify/latex2e.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/gify/lew-7vs.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/gify/lew.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/gify/mail.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/gify/podpis.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/gify/prog.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/gify/tex.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/gify/texologia.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/gify/wa.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/idx/day.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/idx/decode.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/idx/dies.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/idx/fig1.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/idx/flags.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/idx/id.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/idx/index.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/idx/jedn.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/idx/lang.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/idx/lower.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/idx/mil.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/idx/mon.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/idx/name.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/idx/order.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/idx/plmindex.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/idx/porzadek.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/idx/program.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/idx/setki.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/idx/spec.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/idx/tex-idx.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/idx/toascii.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/idx/typy.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/idx/tys.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/idx/upper.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/index.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/kuchnia/hist.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/kuchnia/tex.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/latex2e.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/listy/desc_p1.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/listy/desc_p2.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/listy/desc_p3.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/listy/desc_p4.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/listy/description.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/listy/description.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/listy/enum_p1.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/listy/enum_p2.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/listy/enumerate.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/listy/enumerate.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/listy/item_p1.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/listy/item_p2.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/listy/itemize.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/listy/itemize.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/listy/klopoty.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/listy/list.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/listy/lista_p.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/listy/porzadek.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/listy/standard.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/3parttab.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/3parttable.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/BAhhline.png
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/accent.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/accents.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/acromake.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/acromake.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/afterpage.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/alltt.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/amsthm.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/amsthm1.png
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/amsthm2.png
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/arabic.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/array.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/balance.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/bar.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/bar1.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/bar2.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/bbm.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/bbm1.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/bbm2.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/bbm3.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/bbm4.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/bbm5.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/bbm6.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/bbma.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/bbmb.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/blk1.png
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/blk2.png
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/blk3.png
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/blk4.png
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/blk5.png
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/blk6.png
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/blk7.png
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/blk8.png
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/blk9.png
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/blkarray.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/bm.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/bophook.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/boxedminipage.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/boxm.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/calc.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/calc1.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/calc2.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/capt-of.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/caption.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/caption2.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/case1.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/case2.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/cases.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/ccapt1.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/ccaption.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/changebar.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/chapterbib.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/cite.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/color.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/color.png
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/colortbl.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/comma.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/cute1.png
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/cuted.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/dblcol.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/dblfnote.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/dcolumn.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/delarray.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/delarray.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/deleq.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/deleq1.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/deleq10.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/deleq11.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/deleq12.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/deleq13.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/deleq14.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/deleq15.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/deleq2.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/deleq3.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/deleq4.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/deleq5.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/deleq6.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/deleq7.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/deleq8.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/deleq9.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/diam.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/dotseqn.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/dotseqn.png
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/dow.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/drftcite.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/dropp1.png
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/dropping.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/easyeqn.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/easyeqn1.png
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/easyeqn10.png
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/easyeqn11.png
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/easyeqn12.png
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/easyeqn13.png
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/easyeqn14.png
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/easyeqn15.png
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/easyeqn16.png
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/easyeqn17.png
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/easyeqn2.png
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/easyeqn3.png
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/easyeqn4.png
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/easyeqn5.png
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/easyeqn6.png
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/easyeqn7.png
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/easyeqn8.png
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/easyeqn9.png
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/endfloat.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/enum.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/enumerate.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/enumitem.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/epsfig.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/everyship.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/expdlist.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/exscale.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/extmath.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/extramarks.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/fancb1.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/fancb2.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/fancb3.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/fancb4.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/fancb5.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/fancb6.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/fancb7.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/fancb8.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/fancybox.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/fancyhdr.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/fancyheading.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/filecontents.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/flafter.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/float.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/floatflt.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/floatpag.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/flt1.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/flt2.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/fltpage.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/flushend.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/fn2end.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/fnpara.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/fnpara.png
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/fnpos.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/footmisc.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/footmisc1.png
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/footmisc2.png
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/footnpag.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/fp.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/ftnright.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/geom1.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/geom1.png
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/geom2.png
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/geometry.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/graphicx.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/graphpaper.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/harp1.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/harp2.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/harp3.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/harp4.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/harp5.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/harp6.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/harp7.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/harp8.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/harpoon.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/heart.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/here.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/hhline.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/hhline.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/hyperref.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/ifthen.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/ifthen1.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/ifthen2.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/indentfirst.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/index.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/labeldeb.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/lastpage.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/lcg.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/legend.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/letter.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/letterspace.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/listpart.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/localloc.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/longtable.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/lscape.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/lt1.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/ltablex.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/ltabptch.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/ltxtable.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/macro.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/macro_t.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/manyfoot.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/manyfoot1.png
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/minitoc.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/moje_typy.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/moreverb.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/mparhack.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/multfoot.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/multfoot1.png
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/multfoot2.png
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/multibox.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/multibox.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/multicol.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/multirow.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/multirow1.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/multirow2.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/multirow3.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/multirow4.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/multirow5.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/mycss.css
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/num.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/numprint.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/nut.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/oldst1.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/oldstyle.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/oubraces.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/overbrace.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/overbrace1.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/pdfscreen.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/pfnote.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/plain.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/printtim.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/pstcol.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/q1.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/qobitree.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/ragged2e.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/regcount.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/relsize.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/remreset.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/rotate.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/rotating.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/rotbox.png
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/selectpage.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/shadepar.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/shadetheorem.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/shadethm.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/shadethm.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/shadow.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/shapepar.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/shedbox.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/shortvrb.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/showkeys.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/sidecap.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/squa.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/stm1.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/stm2.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/stm3.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/stm4.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/stmaryrd.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/sube1.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/subeqn-1.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/subeqn-2.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/subeqn-3.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/subeqn.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/subeqna.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/subeqnarray.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/subfig.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/subfigure.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/subfloat.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/sublabel.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/sublabel.png
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/subscript.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/supertabular.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/sverb.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/sverb_n.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/sverb_w.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/tabularx.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/tabularx.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/theorem.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/theorem.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/threeparttable.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/time.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/ulem.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/ulem.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/ulem1.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/umoline.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/undertilde-1.png
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/undertilde.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/url.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/verbatim.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/verbdef.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/verbt.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/verbt1.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/verbt2.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/version.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/vfrlocal.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/vmargin.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/vrbexin.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/vrflocal.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/wiggly.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/wmcropmark.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/wrapf.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/wrapfig.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/xr.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/xspace.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/xspace1.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/xspace2.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/macro/xtab.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/pagina/pagina.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/spisy/chap.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/spisy/l_chap.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/spisy/l_sec.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/spisy/spis.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/spisy/spis.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/tytuly/chapter.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/tytuly/count.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/tytuly/liczniki.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/tytuly/num.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/tytuly/p1.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/tytuly/p2.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/tytuly/p3.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/tytuly/p3.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/tytuly/p4.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/tytuly/p4.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/tytuly/p5.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/tytuly/p5.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/tytuly/p6.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/tytuly/p6.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/tytuly/p7.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/tytuly/p7.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/tytuly/part.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/tytuly/poziom.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/tytuly/s.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/tytuly/sect.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/tytuly/tc.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/tytuly/tc.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/tytuly/tca.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/tytuly/tl.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/tytuly/tl.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/tytuly/tr.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/tytuly/tr.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/tytuly/tx.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/tytuly/tx.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/tytuly/txx.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/latex2e/tytuly/txx.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/manifest.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/poczatki/cont-pl.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/poczatki/emtex.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/poczatki/implementacje.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/poczatki/index.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/poczatki/inst-mik.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/poczatki/latex-pl.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/poczatki/mex.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/poczatki/miktex.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/poczatki/spw.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/poczatki/tetex.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/poczatki/web2c.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/podstawy/2-0wst1.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/podstawy/2-1coto.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/podstawy/2-1kazio.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/podstawy/2-1przyg.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/podstawy/2-1zece.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/podstawy/bib.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/podstawy/spis.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/podstawy/tex.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/podstawy/title.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/prog/auctex.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/prog/bibtex/bibtex-1.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/prog/bibtex/bibtex-2.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/prog/bibtex/bibtex-3.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/prog/bibtex/bibtex-4.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/prog/bibtex/bibtex-5.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/prog/bibtex/bibtex-6.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/prog/bibtex/bibtex-7.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/prog/bibtex/bibtex-8.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/prog/bibtex/bibtex.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/prog/dvidvi.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/prog/dvistro1.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/prog/dvistro2.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/prog/hyph.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/prog/prog.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/tex/fermat.gif
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/tex/odsylacze.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/tex/tex.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/tex/tex_key.html
%doc %{_texmfdistdir}/doc/generic/tex-virtual-academy-pl/tex/tryby.html

#-----------------------------------------------------------------------
%prep
%setup -c -a0 -a1

%build

%install
mkdir -p %{buildroot}%{_texmfdistdir}
cp -fpar doc %{buildroot}%{_texmfdistdir}
